# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classifyIt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(479, 474)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 430, 80, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.closeIt)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 390, 241, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.classifyIt)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 10, 261, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 421, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("waveform.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.movie = QtGui.QMovie("waveform.gif")
        self.label_2.setMovie(self.movie)
        self.movie.start()
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(290, 200, 161, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 230, 161, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 200, 261, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 241, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 260, 261, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(290, 260, 161, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 290, 161, 23))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 241, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 320, 261, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(290, 320, 161, 23))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(290, 350, 161, 23))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 350, 241, 31))
        self.label_8.setObjectName("label_8")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 430, 241, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.clusterIt)
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(350, 390, 120, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.heatmapIt)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BabbittLab@RIT"))
        self.pushButton_2.setText(_translate("Dialog", "exit"))
        self.pushButton_4.setText(_translate("Dialog", "RF class - feature importance"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#555500;\">POPSTAR - Classify</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of folder 1</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of folder 2</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of folder 3</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of folder 4</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of folder 5</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of folder 6</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Dialog", "FDA class - time series"))
        self.pushButton_6.setText(_translate("Dialog", "heatmap CES"))

    
    def closeIt(self):
        print("POPSTAR program closed")
        sys.exit(app.exec_())
    
    def heatmapIt(self):
        print("making heatmap for CES signals")
        cmd = "python3 CESheatmap.py"
        os.system(cmd)
        
    def classifyIt(self):
        print("running RF classifier")
        filename1 = self.lineEdit.text()
        filename2 = self.lineEdit_2.text()
        filename3 = self.lineEdit_3.text()
        filename4 = self.lineEdit_4.text()
        filename5 = self.lineEdit_5.text()
        filename6 = self.lineEdit_6.text()
        f = open("./popstar-classify.ctl", "w") 
        f.write("folder1,%s,#reference folder to analyze\n" % filename1)
        f.write("folder2,%s,#query folder to analyze\n" % filename2)
        f.write("folder3,%s,#reference folder to analyze\n" % filename3)
        f.write("folder4,%s,#query folder to analyze\n" % filename4)
        f.write("folder5,%s,#reference folder to analyze\n" % filename5)
        f.write("folder6,%s,#query folder to analyze\n" % filename6)
        f.close()
        cmd = "python3 classifyFeatures.py"
        os.system(cmd)
    
    def clusterIt(self):
        print("running FDA signature clustering analysis")
        filename1 = self.lineEdit.text()
        filename2 = self.lineEdit_2.text()
        filename3 = self.lineEdit_3.text()
        filename4 = self.lineEdit_4.text()
        filename5 = self.lineEdit_5.text()
        filename6 = self.lineEdit_6.text()
        f = open("./popstar-classify.ctl", "w") 
        f.write("folder1,%s,#reference folder to analyze\n" % filename1)
        f.write("folder2,%s,#query folder to analyze\n" % filename2)
        f.write("folder3,%s,#reference folder to analyze\n" % filename3)
        f.write("folder4,%s,#query folder to analyze\n" % filename4)
        f.write("folder5,%s,#reference folder to analyze\n" % filename5)
        f.write("folder6,%s,#query folder to analyze\n" % filename6)
        f.close()
        cmd = "python3 clusterFeatures.py"
        os.system(cmd)


if __name__ == "__main__":
    import sys
    import os
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
