# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compareIt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(479, 432)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 380, 80, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.closeIt)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 330, 351, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.compareSignal)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 280, 351, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.compareDist)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 10, 351, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 421, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("waveform.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.movie = QtGui.QMovie("waveform.gif")
        self.label_2.setMovie(self.movie)
        self.movie.start()
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(290, 240, 161, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 200, 161, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 200, 261, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 241, 31))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BabbittLab@RIT"))
        self.pushButton_2.setText(_translate("Dialog", "exit"))
        self.pushButton_3.setText(_translate("Dialog", "compare fitness (energy, control, surprise)"))
        self.pushButton_4.setText(_translate("Dialog", "compare step distributions"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#555500;\">POPSTAR - Comparison</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of folder 1 (reference)</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of folder 2 (query)</span></p></body></html>"))

####################################################
    def closeIt(self):
        print("POPSTAR program closed")
        sys.exit(app.exec_())
    
    def compareDist(self):
        print("compare step distributions")
        print("appending control file")
        filename1 = self.lineEdit.text()
        filename2 = self.lineEdit_2.text()
        f = open("./popstar-compare.ctl", "w") 
        f.write("folder1,%s,#reference folder to analyze\n" % filename1)
        f.write("folder2,%s,#query folder to analyze\n" % filename2)
        f.close()
        cmd = "python3 compareDist.py"
        os.system(cmd)
        
    def compareSignal(self):
        print("compare fitness signal features")
        print("appending control file")
        filename1 = self.lineEdit.text()
        filename2 = self.lineEdit_2.text()
        f = open("./popstar-compare.ctl", "w") 
        f.write("folder1,%s,#reference folder to analyze\n" % filename1)
        f.write("folder2,%s,#query folder to analyze\n" % filename2)
        f.close()
        cmd = "python3 compareSignal.py"
        os.system(cmd)

if __name__ == "__main__":
    import os
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
