# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popstar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#############################################################################
######   POPSTAR software for detecting fitness signaling in music
######   produced by Dr. Gregory A. Babbitt
######   and students at the Rochester Instituteof Technology in 2025.
######   Offered freely without guarantee.  License under GPL v3.0
#############################################################################


from PyQt5 import QtCore, QtGui, QtWidgets
import time

selfOption = "no"
spchOption = "no"
musiOption = "no"

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(479, 676)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 530, 171, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.makeFace)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 620, 50, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.closeIt)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 490, 157, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.analyzeSignal)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 490, 171, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.processSound)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(30, 620, 215, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 10, 351, 31))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 530, 171, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.makeMovie)
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 570, 171, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.playFace)
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 570, 171, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.playTraj)
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 570, 80, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.readDoc)
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(390, 530, 80, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.makeHist)
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(335, 620, 80, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.compareIt)
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(250, 620, 80, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.classifyIt)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 421, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("waveform.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.movie = QtGui.QMovie("waveform.gif")
        self.label_2.setMovie(self.movie)
        self.movie.start()
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 190, 421, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(250, 450, 110, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 420, 110, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit.setText("8")
        self.lineEdit_2.setText("test.mp3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 420, 261, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 450, 271, 31))
        self.label_4.setObjectName("label_4")
        # beat tracker box
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(375, 490, 80, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.setChecked(True)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(395, 490, 80, 31))
        self.label_7.setText("beats?")       
        
        ### picture window
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 421, 221))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("starDavid.JPG"))
        self.label_5.setScaledContents(True)
        ###########################################
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(365, 410, 100, 31))
        self.label_6.setObjectName("label_6")
        
        # Radio button for self normalization option
        self.radioButton_self = QtWidgets.QRadioButton(Dialog)
        self.radioButton_self.setGeometry(QtCore.QRect(375, 470, 80, 31))
        # adding signal and slot 
        self.radioButton_self.toggled.connect(self.selfselected)
        self.radioButton_self.setText("single")
        # Radio button for speech normalization option
        self.radioButton_spch = QtWidgets.QRadioButton(Dialog)
        self.radioButton_spch.setGeometry(QtCore.QRect(375, 450, 80, 31))
        # adding signal and slot 
        self.radioButton_spch.toggled.connect(self.spchselected)
        self.radioButton_spch.setText("other")
        # Radio button for music normalization option
        self.radioButton_musi = QtWidgets.QRadioButton(Dialog)
        self.radioButton_musi.setGeometry(QtCore.QRect(375, 430, 80, 31))
        # adding signal and slot 
        self.radioButton_musi.toggled.connect(self.musiselected)
        self.radioButton_musi.setText("music")
        
        ###########################################
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BabbittLab@RIT"))
        self.pushButton.setText(_translate("Dialog", "3. calculate faces"))
        self.pushButton_2.setText(_translate("Dialog", "exit"))
        self.pushButton_3.setText(_translate("Dialog", "2. analyze signal"))
        self.pushButton_4.setText(_translate("Dialog", "1. process sounds"))
        self.pushButton_6.setText(_translate("Dialog", "6. play faces"))
        self.pushButton_7.setText(_translate("Dialog", "5. play trajectory"))
        self.pushButton_8.setText(_translate("Dialog", "see DOC"))
        self.pushButton_9.setText(_translate("Dialog", "p-value"))
        self.pushButton_10.setText(_translate("Dialog", "compare"))
        self.pushButton_11.setText(_translate("Dialog", "classify"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#555500;\">POPSTAR - BabbittLab@RIT</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Dialog", "4. make movies"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">name of file (or folder) </span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">window length (seconds)</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:500;\">sound-type</span></p></body></html>"))
######################################### subroutines ######################################################
    def selfselected(self, selected):
        if selected:
            self.label.setText("self-normalization is now selected")
            global selfOption
            global spchOption
            global musiOption
            selfOption = "yes"
            spchOption = "no"
            musiOption = "no"
            
    def spchselected(self, selected):
        if selected:
            self.label.setText("speech-normalization is now selected")
            global selfOption
            global spchOption
            global musiOption
            selfOption = "no"
            spchOption = "yes"
            musiOption = "no"
               
    def musiselected(self, selected):
        if selected:
            self.label.setText("music-normalization is now selected")
            global selfOption
            global spchOption
            global musiOption
            selfOption = "no"
            spchOption = "no"
            musiOption = "yes"
            
    def closeIt(self):
        print("POPSTAR program closed")
        sys.exit(app.exec_())
    
    def readDoc(self):
        print("POPSTAR instructions")
        cmd = "xdg-open POPSTAR-instructions.pdf" 
        os.system(cmd)
        
    def makeFace(self):
        print("making Chernoff faces")
        cmd = "python3 makeFace.py"
        os.system(cmd)
        for i in range(76): 
            time.sleep(0.01) 
            # setting value to progress bar 
            self.progressBar.setValue(i)
    
    def makeHist(self):
        print("making histogram")
        cmd = "python3 makeHisto.py"
        os.system(cmd)
    
            
    def analyzeSignal(self):
        print("analyzing fitness signal")
        cmd = "python3 analyzeSignal.py"
        os.system(cmd)
        for i in range(51): 
            time.sleep(0.01) 
            # setting value to progress bar 
            self.progressBar.setValue(i)
        
    def processSound(self):
        print("making control file")
        filename = self.lineEdit_2.text()
        if os.path.isfile(filename):
            print("user input is a file")
            fileORfolder = "file"
            filename = filename[:-4]
        if os.path.isdir(filename):
            print("user input is a folder")
            fileORfolder = "folder"
        if self.checkBox.isChecked() == True:
            metroOption = "yes" 
        elif self.checkBox.isChecked() == False:
            metroOption = "no"
        '''
        if self.checkBox_2.isChecked() == True:
            spchOption = "yes" 
        elif self.checkBox_2.isChecked() == False:
            spchOption = "no"
        if self.checkBox_3.isChecked() == True:
            selfOption = "yes" 
        elif self.checkBox_3.isChecked() == False:
            selfOption = "no"   
        '''
        if(selfOption == "no" and spchOption == "no" and musiOption == "no"):
            print("\nWARNING - you must choose a sound-type option prior to run")
            print("...open interface and try again, ... will close in 5s\n")
            time.sleep(5)
            exit()
        if(selfOption == "yes" and fileORfolder == "folder"):
            print("\nWARNING - comparative analysis requires 'single' sound-typw be NOT SELECTED")
            print("The 'single' sound-type option normalizes the fitness signal within each sound file")
            print("Thus, it is best used when analyzing changes within a single file")
            print("When 'single' is not chosen, all fitness signals are normalized ")
            print("to average feature values observed in human speech (= other) or music (= music)")
            print("Thus, these options are best when intending to compare many files grouped in folders")
            print("...press (ctl+c) to stop, otherwise the analysis will start in 20s\n")
            time.sleep(20)        
        interval = self.lineEdit.text()
        f = open("./popstar.ctl", "w") 
        f.write("name,%s,#file or folder name to analyze\n" % filename)
        f.write("int,%s,#size of sliding window (seconds)\n" % interval)
        f.write("input,%s,#input type\n" % fileORfolder)
        f.write("metro,%s,#use metronome\n" % metroOption)
        f.write("spch,%s,#normalize to human speech average\n" % spchOption)
        f.write("musi,%s,#normalize to human music average\n" % musiOption)
        f.write("self,%s,#self normalize to the song center value\n" % selfOption)
        f.close()
        print("pre-processing sound file(s)")
        # setting for loop to set value of progress bar 
        cmd = "python3 processSound.py"
        os.system(cmd)
        for i in range(26): 
            time.sleep(0.01) 
            # setting value to progress bar 
            self.progressBar.setValue(i)
            
    def makeMovie(self):
        print("rendering movie file")
        cmd = "python3 makeMovie.py"
        os.system(cmd)
        for i in range(101): 
            time.sleep(0.01) 
            # setting value to progress bar 
            self.progressBar.setValue(i)
    
    def playFace(self):
        print("playing movie file")
        cmd = "python3 playFaceMovie.py"
        os.system(cmd)
        
    def playTraj(self):
        print("playing movie file")
        cmd = "python3 playTplotMovie.py"
        os.system(cmd)
        
    def classifyIt(self):
        print("random forest classification of two or more folders")
        cmd = "python3 classifyIt.py"
        os.system(cmd)
        
    def compareIt(self):
        print("statistical comparison of two folders")
        cmd = "python3 compareIt.py"
        os.system(cmd)
###########################################################################################################
###########################################################################################################

if __name__ == "__main__":
    import os
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

############################################################################################################



